### ISSUE TITLE
gc简化

### ISSUE THREAD

**Issue by lylei** [bluebore/dfs#106]
由于后续开发，原gc逻辑有些冗余设计。简化思路：如果在mapping里找不到cs上报的block，直接在response里要求cs删掉该block。

**Comment by yvxiang** [comment]
现在处理BlockReport时不就是这样的吗？
你是说删除时不放到obsolete_blocks里了？

**Comment by lylei** [comment]
恩，感觉没有必要先放进obsolete_blocks了，直接删了就行。

**Comment by yvxiang** [comment]
放进去有一个好处，就是后续可以实现类似回收站的功能，过了一定时间才真正的删

**Comment by lylei** [comment]
你提到的回收站功能应该是文件级别的，这个应该主要是在ns端做处理，不应该涉及到具体数据块。而gc针对的是例如多余副本，过期数据块等。

**Comment by lylei** [comment]
build
