### ISSUE TITLE
全异步写 & 增量report

### ISSUE THREAD

**Issue by linyvxiang** [bluebore/dfs#43]
docs/README.md中提到chunkserver支持全异步写，请问一下这是什么意思？是DiskWrite()时用POSIX AIO吗？还是说在RPC时就把数据流和指令流分开？
还有增量report，这个之前提到过一次，是说对所有block进行分批report呢还是说只在block有变动时报告增量？

**Comment by bluebore** [comment]
前者我正在做，当前写流程中有很多是同步阻塞的，比如open block文件、将blockbuf写入磁盘，会造成很大的延迟，导致写吞吐无法达到理论值，我打算提供一种模式将整个写入流程做成无阻塞的，将单文件写入吞吐提升到100MB+
增量report打算是做成分批report。

**Comment by linyvxiang** [comment]
了解。
那我试着实现一下分批report
