### ISSUE TITLE
文件描述符关闭

### ISSUE THREAD

**Issue by linyvxiang** [bluebore/dfs#47]
目前chunkserver中唯一关闭文件描述符的地方是Block的析构函数。而当前内核对于每个用户进程的最大打开文件数是有限制的。即使修改了限制，也会造成系统资源的浪费。是否有必要去关闭一些文件呢？

**Comment by bluebore** [comment]
Block没用就析构了，资源泄漏问题不大。
这块确实需要一个LRU cache

**Comment by linyvxiang** [comment]
但是block被放到_block_map中时，会增加一次引用计数，这将导致只要在chunkserver运行时，block便不会被析构，即使这个block被close。

**Comment by linyvxiang** [comment]
仔细看了下代码，close block是没有问题的，问题主要出现在读文件的时候。我先实现一个LRU。
