### ISSUE TITLE
扇出写支持

### ISSUE THREAD

**Issue by linyvxiang** [bluebore/dfs#80]
我看到TODO中有一项是　扇出写支持　这个是什么意思？
另外，那天的core怎么样了？

**Comment by bluebore** [comment]
那个我修了，这两天其他事略多，没提交。
扇出写的意思是，sdk直接写3个chunkserver，而不是写给一个chunkserver，让它给其他的发。
主要好处是可以避免慢节点，比如nameserver可以返回给sdk4个cs，sdk同时写，有3个写成功了就可以关闭文件，让nameserver把另外一个写的慢的block垃圾回收掉就行。而链式写，有一个慢，整体的都慢。

**Comment by linyvxiang** [comment]
那这样的话不用担心sdk的吞吐吗？

**Comment by linyvxiang** [comment]
#81
