### ISSUE TITLE
副本数保持

### ISSUE THREAD

**Issue by yvxiang** [bluebore/dfs#87]
当前一旦认为某个chunkserver挂掉后，便会在下一次接收到block report时考虑副本复制。是不是有必要将复制动作稍微推迟一些，毕竟有可能过了一分多钟机器又起来了

**Comment by bluebore** [comment]
我觉得没必要,原因有两点,认为chunkserver挂掉是有个心跳超时的,这个超时可以涵盖这个一分钟的抖动;即使又起来了,可以取消进行中的复制任务.
